### ISSUE TITLE
Video screen is coming over the buttons, the live meeting screen also not showing the other device video

### ISSUE THREAD

**Issue by isahilbisht** [100mslive/100ms-flutter#752]
i am trying to have a video call from flutter application but the user video is not coming over the difficult to click the buttons and in the meeting page the video from the other device is not visible untill i turn my video off. It is showing only one end video response on the page and the video coming also not showing in the specified area.

**Comment by Decoder07** [comment]
Hi @isahilbisht are you using flutter 3.0 ?

**Comment by ygit** [comment]
@isahilbisht This issue is likely happening due to usage of Flutter 3.x.x series.
Use a version of the 2.x.x series, 2.10.5 or lower.

This is due to an ongoing issue in Flutter 3.x.x which causes Native Platform Views to be drawn at incorrect position. 
Refer: [107313](https://github.com/flutter/flutter/issues/107313) & [103630](https://github.com/flutter/flutter/issues/103630). 

We are actively tracking these issues & once they are released on Flutter [`stable`](https://github.com/flutter/flutter/tree/stable) branch, we'll release a compatible `hmssdk_flutter` version.

**Comment by ygit** [comment]
@isahilbisht Were you able to resolve this issue?

**Comment by isahilbisht** [comment]
Yes I was able to resolve the issue, I have downgrade my flutter to 2.10.5
and the issue was resolved. Thank you for your support.

**Comment by ygit** [comment]
@isahilbisht Awesome 👍
