### ISSUE TITLE
NullPointerException   live.hms.hmssdk_flutter.views.HMSVideoViewFactory in create

### ISSUE THREAD

**Issue by abbas2501** [100mslive/100ms-flutter#881]
![image](https://user-images.githubusercontent.com/93256186/196112027-31d52708-d6dd-4a06-9bfa-dd0a95e0c9e0.png)

**Comment by Decoder07** [comment]
@abbas2501  I am not able to see the issue can you please update the issue.

**Comment by abbas2501** [comment]
> @abbas2501 I am not able to see the issue can you please update the issue.

Yes, the image seems to be missing. Reuploading here - 

```

live.hms.hmssdk_flutter.views.HMSVideoViewFactory in create at line 8
io.flutter.plugin.platform.o$a in d at line 10
io.flutter.embedding.engine.j.k$a in b at line 19
io.flutter.embedding.engine.j.k$a in onMethodCall at line 12
n.a.d.a.k$a in a at line 2
io.flutter.embedding.engine.f.e in k at line 2
io.flutter.embedding.engine.f.e in l at line 2
io.flutter.embedding.engine.f.e in m
io.flutter.embedding.engine.f.c in run at line 12
android.os.Handler in handleCallback at line 938
android.os.Handler in dispatchMessage at line 99
android.os.Looper in loop at line 233
android.app.ActivityThread in main at line 8068
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 631
com.android.internal.os.ZygoteInit in main at line 978
```


![image](https://user-images.githubusercontent.com/93256186/196366287-3ce1f120-dd1a-4c4d-96eb-a993aacd987b.png)



![image](https://user-images.githubusercontent.com/93256186/196366360-adbf332c-9e71-45de-b845-eaab25cd765e.png)

**Comment by Decoder07** [comment]
When are you getting this ?

**Comment by abbas2501** [comment]
> Can you share when you get this error ?

Not sure again, because the issue got caught in release mode on sentry. I'll update this thread if I've more information for you.

**Comment by ygit** [comment]
hey @abbas2501 
Were you able to resolve this issue?

**Comment by joshmossas** [comment]
Hello we've been running into this issue very consistently on Android.

It happens when we try to reuse an HMSSDK instance between rooms. Basically if you call `sdk.leave()` and then later try to preview that room again we get a NullPointerException when the `HMSVideoView` widget to render.

The way we've been getting around this is creating a new HMSSDK instance and running `sdk.build()` whenever entering a new room, but it's not ideal since it slows down the user experience.

**Comment by ygit** [comment]
hey @joshmossas 
While calling the `sdk.leave()` function, do pass `HMSActionResultListener` & perform preview/rejoin, etc operations in the `success` of the action result listener. 
This ensures that the room has been cleanly left.

Do Refer: https://www.100ms.live/docs/flutter/v2/features/leave

**Comment by joshmossas** [comment]
We are doing `await sdk.leave()`. I would expect that the future completes when the room is successfully left and then throws an exception if the room has not been cleanly left. Is this not the case?

**Comment by joshmossas** [comment]
Hey @ygit 

So I looked into it further and played around with a basic implementation using the `HMSActionResultListener`, and what I've found is that even after the `onSuccess` method is called with the methodType `HMSActionResultListenerMethod.leave` this error still occurs. 

Specifically it occurs when a preview instance tries to render a `HMSVideoView` widget after a room has been left. It doesn't need to be the same room it can be after you have left any room. When I comment out the HMSVideoView widget on the preview screen I no longer encounter this error. (The other actions such as toggling mic, video, and stuff still work)

For some reason when creating the HMSVideoView a null pointer is being reference on the Kotlin side.

**Comment by ygit** [comment]
hey @joshmossas 
Let's connect over a call to discuss this. 
Do book a convenient time here: https://calendly.com/yogesh-singh-100ms/30min

**Comment by joshmossas** [comment]
@ygit thanks for the calendar link. 

After looking into it further I was able to find the issue on our end. We had an autodispose riverpod provider (which was holding an instance of the HMSSDK) that was being created and disposed too deep into the widget tree and that was causing funny behaviors. Moving the provider's initialization into `initState` and moving the initial `ref.watch` instances to the start of the build method fixed the issue we were having. We can now reuse the HMSSDK instance across rooms without running into a NullPointerException

However there are still a couple weird behaviors. For example if we remove `.autoDispose` from our provider we start getting the Null pointer exception again. Because of this I decided to book a time with you anyway. Maybe you can point out something we are doing wrong. Thanks

**Comment by ygit** [comment]
Sure @joshmossas 
We'll connect over the call. 
Also, we also have a Riverpod Example app, do refer to it once: https://github.com/100mslive/100ms-flutter/tree/main/sample%20apps/riverpod

**Comment by joshmossas** [comment]
If anyone else that runs into this. This the bug was caused by bad state. All HMSTracks no longer exist after you leave a room / end a preview so you should clean up that state after leaving the room (or destroy that provider / class instance).

If you try to reference one of those tracks again HMS will throw a NullPointerException when trying to create the HMSVideoView since that track no longer exists.

This issue can probably be closed IMHO.

**Comment by ygit** [comment]
Thanks @joshmossas
